#pragma once

// SPDX-License-Identifier: MIT
// Copyright (c) 2026 Eric M. Kok
// AUTO-GENERATED by pre_build.ps1 - do not edit by hand.
// Rebuilt on every build from files/lang_*.h.

#include "files/lang_en.h"
#include "files/lang_nl.h"

static const LangStrings* const LANGUAGES[] = {
    &lang_en,
    &lang_nl,
};
#define LANGUAGE_COUNT (sizeof(LANGUAGES) / sizeof(LANGUAGES[0]))

