/*
 * OTPvault - Flipper Zero app
 * Copyright (c) 2026 Eric M. Kok
 * SPDX-License-Identifier: MIT
 * See LICENSE in this app's folder for the full license text.
 *
 * Password-protected TOTP vault. The accounts are stored in one file that is
 * encrypted with AES-256-GCM. The key is derived from the password with
 * PBKDF2-HMAC-SHA256 and then passed through this Flipper's secure-enclave
 * key, so the file can only be opened on this device and only with the
 * password. Codes are typed over USB as a keyboard.
 */

#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_usb_hid.h>
#include <gui/gui.h>
#include <input/input.h>
#include <storage/storage.h>
#include <flipper_format/flipper_format.h>
#include <datetime/datetime.h>

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "sha.h"
#include "otp.h"

#define APP_VERSION "1.03"
#define APP_START_YEAR 2026
#define APP_AUTHOR "Eric M. Kok"
#define APP_LICENSE "MIT"

#define DATA_DIR EXT_PATH("apps_data/otp_vault")
#define VAULT_PATH DATA_DIR "/vault.bin"
#define VAULT_TMP_PATH DATA_DIR "/vault.tmp"
#define SETTINGS_PATH DATA_DIR "/settings.cfg"
#define IMPORT_PATH DATA_DIR "/import.txt"

#define IMPORT_MAX 4096

// Vault file layout: header | tag | ciphertext. The header (magic, version,
// iterations, salt, IV) is authenticated as GCM additional data.
#define VAULT_MAGIC "OTPV"
#define VAULT_VERSION 1
#define MAX_ACCOUNTS 16
#define NAME_LEN 24
#define SECRET_MAX 64
#define REC_LEN (NAME_LEN + 4 + SECRET_MAX)
#define PLAIN_LEN (1 + MAX_ACCOUNTS * REC_LEN)
#define SALT_LEN 16
#define IV_LEN 12
#define TAG_LEN 16
#define HDR_LEN (4 + 1 + 4 + SALT_LEN + IV_LEN)
#define FILE_LEN (HDR_LEN + TAG_LEN + PLAIN_LEN)

#define PW_MAX 16
#define PW_MIN 8
#define KDF_TARGET_MS 1500
#define KDF_MIN_ITERS 10000u
#define KDF_MAX_ITERS 500000u

#define PAGE_CODES 0
#define PAGE_IMPORT 1
#define PAGE_SETTINGS 2
#define PAGE_HELP 3
#define PAGE_ABOUT 4
#define PAGE_COUNT 5

#define SETTINGS_ROWS 4
#define SET_LANGUAGE 0
#define SET_UTC 1
#define SET_DIGITS 2
#define SET_LOCK 3

#define UTC_MIN_MINUTES (-720)
#define UTC_MAX_MINUTES 840

static const char PW_CHARSET[] =
    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%&*-_.+=?:/";
static const uint16_t LOCK_SECONDS[] = {15, 30, 60, 120, 300, 600, 900, 1800};
#define LOCK_DEFAULT_IDX 2
#define LOCK_COUNT (sizeof(LOCK_SECONDS) / sizeof(LOCK_SECONDS[0]))

//======================================================================================================================
// Language strings (one files/lang_<code>.h per language, see pre_build.ps1)
//======================================================================================================================

typedef struct {
    const char* lang_name;

    const char* title_codes;
    const char* title_import;
    const char* title_settings;
    const char* title_help;
    const char* title_about;
    const char* title_unlock;
    const char* title_create;
    const char* title_confirm;

    const char* pw_hint1;
    const char* pw_hint2;
    const char* pw_hint3;

    const char* msg_wrong;
    const char* msg_mismatch;
    const char* msg_short;
    const char* msg_working;
    const char* msg_wait; // "%lu" = seconds
    const char* msg_selftest_fail;
    const char* err_title;
    const char* err_use;
    const char* err_step; // "%u" = failing step
    const char* err_exit;
    const char* msg_no_usb;
    const char* msg_typed;
    const char* msg_corrupt;
    const char* msg_save_fail;

    const char* no_accounts;
    const char* no_accounts_hint;
    const char* clock_warn;
    const char* hint_type;

    const char* imp_1;
    const char* imp_2;
    const char* imp_3;
    const char* imp_ok;
    const char* imp_done; // "%u" = number imported
    const char* imp_none;
    const char* imp_bad; // "%u" = line number
    const char* imp_full;

    const char* lbl_language;
    const char* lbl_utc;
    const char* lbl_digits;
    const char* lbl_lock;
    const char* digits_top;
    const char* digits_pad;

    const char* help_1;
    const char* help_2;
    const char* help_3;
    const char* help_4;
    const char* help_5;

    const char* about_version;
    const char* about_author;
    const char* about_copyright;
    const char* about_license;
    const char* about_selftest;
    const char* selftest_ok;
    const char* selftest_fail;
} LangStrings;

// Generated by pre_build.ps1 from files/lang_*.h.
#include "lang_manifest.h"

//======================================================================================================================
// State
//======================================================================================================================

typedef enum {
    ScreenCreate,
    ScreenConfirm,
    ScreenUnlock,
    ScreenMain,
} Screen;

typedef enum {
    ActNone,
    ActCreate,
    ActUnlock,
    ActImport,
    ActType,
} Action;

typedef struct {
    char name[NAME_LEN];
    uint8_t algo;
    uint8_t digits;
    uint8_t period;
    uint8_t secret_len;
    uint8_t secret[SECRET_MAX];
} Account;

typedef struct {
    Gui* gui;
    ViewPort* view_port;
    FuriMessageQueue* queue;
    FuriMutex* mutex;
    Storage* storage;

    Screen screen;
    Action pending;
    bool busy;
    uint8_t page;
    bool selftest_ok;
    uint8_t selftest_step;

    // Settings (stored in plain text, nothing secret).
    uint8_t lang;
    int16_t utc_min;
    uint8_t digits_pad;
    uint8_t lock_idx;
    uint8_t settings_sel;

    // Password entry.
    char pw[PW_MAX + 1];
    char pw_first[PW_MAX + 1];
    uint8_t pw_len;
    uint8_t pw_cur;
    uint32_t fails;
    uint32_t wait_until;

    // Unlocked vault.
    uint8_t salt[SALT_LEN];
    uint32_t iters;
    uint8_t key[32];
    Account acc[MAX_ACCOUNTS];
    uint8_t acc_count;
    uint8_t sel;

    char msg[40];
    uint32_t msg_until;
    uint32_t last_input;
} App;

static void set_msg(App* app, const char* text) {
    snprintf(app->msg, sizeof(app->msg), "%s", text);
    app->msg_until = furi_get_tick() + 2500;
}

static bool is_waiting(const App* app) {
    return (int32_t)(app->wait_until - furi_get_tick()) > 0;
}

//======================================================================================================================
// Self-test (RFC test vectors; proves the own SHA/HMAC/PBKDF2/TOTP code works)
//======================================================================================================================

static bool check_hex(const uint8_t* data, size_t len, const char* expected) {
    static const char hex[] = "0123456789abcdef";
    if(strlen(expected) != len * 2) return false;
    for(size_t i = 0; i < len; i++) {
        if(expected[2 * i] != hex[data[i] >> 4]) return false;
        if(expected[2 * i + 1] != hex[data[i] & 15]) return false;
    }
    return true;
}

// Returns 0 when everything passed, otherwise the number of the failing step.
static uint8_t run_selftest(void) {
    uint8_t d[SHA256_LEN];
    const uint8_t* abc = (const uint8_t*)"abc";
    const uint8_t* jefe = (const uint8_t*)"Jefe";
    const uint8_t* what = (const uint8_t*)"what do ya want for nothing?";
    size_t what_len = strlen("what do ya want for nothing?");
    Sha1 s1;
    Sha256 s2;

    sha1_init(&s1);
    sha1_update(&s1, abc, 3);
    sha1_final(&s1, d);
    if(!check_hex(d, SHA1_LEN, "a9993e364706816aba3e25717850c26c9cd0d89d")) return 1;

    sha256_init(&s2);
    sha256_update(&s2, abc, 3);
    sha256_final(&s2, d);
    if(!check_hex(d, SHA256_LEN, "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"))
        return 2;

    hmac_sha1(jefe, 4, what, what_len, d);
    if(!check_hex(d, SHA1_LEN, "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79")) return 3;

    hmac_sha256(jefe, 4, what, what_len, d);
    if(!check_hex(d, SHA256_LEN, "5bdcc146bf60754e6a042426089575c75a003f089d2739839dec58b964ec3843"))
        return 4;

    pbkdf2_hmac_sha256((const uint8_t*)"password", 8, (const uint8_t*)"salt", 4, 1, d);
    if(!check_hex(d, SHA256_LEN, "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b"))
        return 5;
    pbkdf2_hmac_sha256((const uint8_t*)"password", 8, (const uint8_t*)"salt", 4, 2, d);
    if(!check_hex(d, SHA256_LEN, "ae4d0c95af6b46d32d0adff928f06dd02a303f8ef3c251dfd6e2d85a95474c43"))
        return 6;

    if(totp_code(OtpSha1, (const uint8_t*)"12345678901234567890", 20, 59, 30, 8) != 94287082u)
        return 7;
    if(totp_code(OtpSha256, (const uint8_t*)"12345678901234567890123456789012", 32, 59, 30, 8) !=
       46119246u)
        return 8;

    uint8_t b32[10];
    if(base32_decode("GEZDGNBVGY3TQOJQ", b32, sizeof(b32)) != 10) return 9;
    if(memcmp(b32, "1234567890", 10) != 0) return 9;

    return 0;
}

// Leaves the result next to the vault so it can be read without the screen.
static void selftest_log(App* app) {
    char text[48];
    if(app->selftest_ok) {
        snprintf(text, sizeof(text), "v%s selftest=OK\n", APP_VERSION);
    } else {
        snprintf(text, sizeof(text), "v%s selftest=FAIL step=%u\n", APP_VERSION, app->selftest_step);
    }
    storage_simply_mkdir(app->storage, DATA_DIR);
    // file_write_all is defined further down; open the file directly here.
    File* f = storage_file_alloc(app->storage);
    if(storage_file_open(f, DATA_DIR "/selftest.txt", FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        storage_file_write(f, text, strlen(text));
    }
    storage_file_close(f);
    storage_file_free(f);
}

//======================================================================================================================
// Settings
//======================================================================================================================

static void settings_save(App* app) {
    storage_simply_mkdir(app->storage, DATA_DIR);
    FlipperFormat* ff = flipper_format_file_alloc(app->storage);
    if(flipper_format_file_open_always(ff, SETTINGS_PATH)) {
        uint32_t v;
        flipper_format_write_header_cstr(ff, "OTPvault settings", 1);
        v = app->lang;
        flipper_format_write_uint32(ff, "Language", &v, 1);
        v = (uint32_t)(app->utc_min - UTC_MIN_MINUTES);
        flipper_format_write_uint32(ff, "Utc", &v, 1);
        v = app->digits_pad;
        flipper_format_write_uint32(ff, "Numpad", &v, 1);
        v = LOCK_SECONDS[app->lock_idx];
        flipper_format_write_uint32(ff, "LockSecs", &v, 1);
    }
    flipper_format_free(ff);
}

static void settings_load(App* app) {
    FlipperFormat* ff = flipper_format_file_alloc(app->storage);
    FuriString* header = furi_string_alloc();
    uint32_t version = 0;
    if(flipper_format_file_open_existing(ff, SETTINGS_PATH) &&
       flipper_format_read_header(ff, header, &version)) {
        uint32_t v;
        if(flipper_format_read_uint32(ff, "Language", &v, 1) && v < LANGUAGE_COUNT) {
            app->lang = (uint8_t)v;
        }
        if(flipper_format_read_uint32(ff, "Utc", &v, 1) &&
           v <= (uint32_t)(UTC_MAX_MINUTES - UTC_MIN_MINUTES)) {
            app->utc_min = (int16_t)((int32_t)v + UTC_MIN_MINUTES);
        }
        if(flipper_format_read_uint32(ff, "Numpad", &v, 1)) app->digits_pad = v ? 1 : 0;
        if(flipper_format_read_uint32(ff, "LockSecs", &v, 1)) {
            for(size_t i = 0; i < LOCK_COUNT; i++) {
                if(LOCK_SECONDS[i] == v) app->lock_idx = (uint8_t)i;
            }
        }
    }
    furi_string_free(header);
    flipper_format_free(ff);
}

//======================================================================================================================
// Files and vault
//======================================================================================================================

static bool file_read_all(Storage* st, const char* path, uint8_t* buf, size_t max, size_t* out_len) {
    File* f = storage_file_alloc(st);
    bool ok = false;
    if(storage_file_open(f, path, FSAM_READ, FSOM_OPEN_EXISTING)) {
        *out_len = storage_file_read(f, buf, max);
        ok = true;
    }
    storage_file_close(f);
    storage_file_free(f);
    return ok;
}

static bool file_write_all(Storage* st, const char* path, const uint8_t* buf, size_t len) {
    File* f = storage_file_alloc(st);
    bool ok = false;
    if(storage_file_open(f, path, FSAM_WRITE, FSOM_CREATE_ALWAYS)) {
        ok = storage_file_write(f, buf, len) == len;
    }
    storage_file_close(f);
    storage_file_free(f);
    return ok;
}

// password -> PBKDF2 -> enclave (unique key, slot 11) -> 32-byte vault key.
static bool derive_key(const char* pw, const uint8_t* salt, uint32_t iters, uint8_t* key_out) {
    uint8_t k1[32];
    static const uint8_t iv0[16] = {0};
    bool ok = false;

    pbkdf2_hmac_sha256((const uint8_t*)pw, strlen(pw), salt, SALT_LEN, iters, k1);

    if(furi_hal_crypto_enclave_ensure_key(FURI_HAL_CRYPTO_ENCLAVE_UNIQUE_KEY_SLOT) &&
       furi_hal_crypto_enclave_load_key(FURI_HAL_CRYPTO_ENCLAVE_UNIQUE_KEY_SLOT, iv0)) {
        ok = furi_hal_crypto_encrypt(k1, key_out, 32);
        furi_hal_crypto_enclave_unload_key(FURI_HAL_CRYPTO_ENCLAVE_UNIQUE_KEY_SLOT);
    }
    secure_zero(k1, sizeof(k1));
    return ok;
}

static uint32_t calibrate_iterations(void) {
    uint8_t salt[SALT_LEN] = {0};
    uint8_t out[32];
    uint32_t t0 = furi_get_tick();
    pbkdf2_hmac_sha256((const uint8_t*)"calibrate", 9, salt, SALT_LEN, 1000, out);
    uint32_t ms = furi_get_tick() - t0;
    if(ms == 0) ms = 1;
    uint64_t iters = (uint64_t)1000 * KDF_TARGET_MS / ms;
    if(iters < KDF_MIN_ITERS) iters = KDF_MIN_ITERS;
    if(iters > KDF_MAX_ITERS) iters = KDF_MAX_ITERS;
    return (uint32_t)iters;
}

static void serialize_accounts(const App* app, uint8_t* plain) {
    memset(plain, 0, PLAIN_LEN);
    plain[0] = app->acc_count;
    for(uint8_t i = 0; i < app->acc_count; i++) {
        uint8_t* r = plain + 1 + i * REC_LEN;
        const Account* a = &app->acc[i];
        memcpy(r, a->name, NAME_LEN);
        r[NAME_LEN] = a->algo;
        r[NAME_LEN + 1] = a->digits;
        r[NAME_LEN + 2] = a->period;
        r[NAME_LEN + 3] = a->secret_len;
        memcpy(r + NAME_LEN + 4, a->secret, SECRET_MAX);
    }
}

static bool parse_accounts(App* app, const uint8_t* plain) {
    if(plain[0] > MAX_ACCOUNTS) return false;
    app->acc_count = plain[0];
    for(uint8_t i = 0; i < app->acc_count; i++) {
        const uint8_t* r = plain + 1 + i * REC_LEN;
        Account* a = &app->acc[i];
        memcpy(a->name, r, NAME_LEN);
        a->name[NAME_LEN - 1] = 0;
        a->algo = r[NAME_LEN];
        a->digits = r[NAME_LEN + 1];
        a->period = r[NAME_LEN + 2];
        a->secret_len = r[NAME_LEN + 3];
        memcpy(a->secret, r + NAME_LEN + 4, SECRET_MAX);
        if(a->algo > OtpSha256 || a->digits < 6 || a->digits > 8 || a->period < 10 ||
           a->period > 120 || a->secret_len == 0 || a->secret_len > SECRET_MAX) {
            return false;
        }
    }
    return true;
}

static bool vault_save(App* app) {
    uint8_t* plain = malloc(PLAIN_LEN);
    uint8_t* file = malloc(FILE_LEN);
    bool ok = false;

    serialize_accounts(app, plain);

    memcpy(file, VAULT_MAGIC, 4);
    file[4] = VAULT_VERSION;
    for(int i = 0; i < 4; i++) file[5 + i] = (uint8_t)(app->iters >> (8 * i));
    memcpy(file + 9, app->salt, SALT_LEN);
    furi_hal_random_fill_buf(file + 9 + SALT_LEN, IV_LEN);

    if(furi_hal_crypto_gcm_encrypt_and_tag(
           app->key,
           file + 9 + SALT_LEN,
           file,
           HDR_LEN,
           plain,
           file + HDR_LEN + TAG_LEN,
           PLAIN_LEN,
           file + HDR_LEN) == FuriHalCryptoGCMStateOk) {
        storage_simply_mkdir(app->storage, DATA_DIR);
        if(file_write_all(app->storage, VAULT_TMP_PATH, file, FILE_LEN)) {
            storage_simply_remove(app->storage, VAULT_PATH);
            ok = storage_common_rename(app->storage, VAULT_TMP_PATH, VAULT_PATH) == FSE_OK;
        }
    }

    secure_zero(plain, PLAIN_LEN);
    free(plain);
    free(file);
    return ok;
}

typedef enum {
    VaultOk,
    VaultCorrupt,
    VaultWrongPassword,
} VaultResult;

static VaultResult vault_load(App* app) {
    uint8_t* file = malloc(FILE_LEN);
    uint8_t* plain = malloc(PLAIN_LEN);
    size_t len = 0;
    VaultResult result = VaultCorrupt;

    if(file_read_all(app->storage, VAULT_PATH, file, FILE_LEN, &len) && len == FILE_LEN &&
       memcmp(file, VAULT_MAGIC, 4) == 0 && file[4] == VAULT_VERSION) {
        uint32_t iters = 0;
        for(int i = 0; i < 4; i++) iters |= (uint32_t)file[5 + i] << (8 * i);
        if(iters >= 1000 && iters <= 2000000u) {
            memcpy(app->salt, file + 9, SALT_LEN);
            app->iters = iters;
            if(derive_key(app->pw, app->salt, iters, app->key)) {
                FuriHalCryptoGCMState st = furi_hal_crypto_gcm_decrypt_and_verify(
                    app->key,
                    file + 9 + SALT_LEN,
                    file,
                    HDR_LEN,
                    file + HDR_LEN + TAG_LEN,
                    plain,
                    PLAIN_LEN,
                    file + HDR_LEN);
                if(st == FuriHalCryptoGCMStateOk) {
                    result = parse_accounts(app, plain) ? VaultOk : VaultCorrupt;
                } else if(st == FuriHalCryptoGCMStateAuthFailure) {
                    result = VaultWrongPassword;
                }
            }
        }
    }

    secure_zero(plain, PLAIN_LEN);
    free(plain);
    free(file);
    if(result != VaultOk) secure_zero(app->key, sizeof(app->key));
    return result;
}

//======================================================================================================================
// Import (import.txt: "Name;BASE32SECRET[;sha1|sha256[;digits[;period]]]" per line)
//======================================================================================================================

static bool str_ieq(const char* a, const char* b) {
    for(; *a && *b; a++, b++) {
        char x = (*a >= 'A' && *a <= 'Z') ? (char)(*a + 32) : *a;
        char y = (*b >= 'A' && *b <= 'Z') ? (char)(*b + 32) : *b;
        if(x != y) return false;
    }
    return *a == *b;
}

static bool parse_import_line(char* line, Account* a) {
    char* fields[5] = {line, NULL, NULL, NULL, NULL};
    int n = 1;
    for(char* p = line; *p && n < 5; p++) {
        if(*p == ';') {
            *p = 0;
            fields[n++] = p + 1;
        }
    }
    if(n < 2 || fields[0][0] == 0) return false;

    memset(a, 0, sizeof(*a));
    snprintf(a->name, NAME_LEN, "%s", fields[0]);

    int len = base32_decode(fields[1], a->secret, SECRET_MAX);
    if(len <= 0) return false;
    a->secret_len = (uint8_t)len;

    a->algo = OtpSha1;
    if(n > 2 && fields[2][0]) {
        if(str_ieq(fields[2], "sha256")) {
            a->algo = OtpSha256;
        } else if(!str_ieq(fields[2], "sha1")) {
            return false;
        }
    }

    a->digits = 6;
    if(n > 3 && fields[3][0]) {
        int v = atoi(fields[3]);
        if(v < 6 || v > 8) return false;
        a->digits = (uint8_t)v;
    }

    a->period = 30;
    if(n > 4 && fields[4][0]) {
        int v = atoi(fields[4]);
        if(v < 10 || v > 120) return false;
        a->period = (uint8_t)v;
    }
    return true;
}

static void action_import(App* app) {
    const LangStrings* s = LANGUAGES[app->lang];
    char text[48];
    char* buf = malloc(IMPORT_MAX + 1);
    size_t len = 0;

    if(!file_read_all(app->storage, IMPORT_PATH, (uint8_t*)buf, IMPORT_MAX, &len)) {
        set_msg(app, s->imp_none);
        free(buf);
        return;
    }
    buf[len] = 0;

    Account added[MAX_ACCOUNTS];
    uint8_t added_count = 0;
    unsigned line_no = 0;
    bool bad = false;
    bool full = false;

    char* line = buf;
    while(line && *line) {
        char* next = strchr(line, '\n');
        if(next) *next++ = 0;
        line_no++;
        size_t ll = strlen(line);
        while(ll && (line[ll - 1] == '\r' || line[ll - 1] == ' ')) line[--ll] = 0;
        if(ll && line[0] != '#') {
            if(app->acc_count + added_count >= MAX_ACCOUNTS) {
                full = true;
                break;
            }
            if(!parse_import_line(line, &added[added_count])) {
                bad = true;
                break;
            }
            added_count++;
        }
        line = next;
    }

    if(bad) {
        snprintf(text, sizeof(text), s->imp_bad, line_no);
        set_msg(app, text);
    } else if(full) {
        set_msg(app, s->imp_full);
    } else if(added_count == 0) {
        set_msg(app, s->imp_none);
    } else {
        uint8_t old_count = app->acc_count;
        for(uint8_t i = 0; i < added_count; i++) app->acc[app->acc_count++] = added[i];
        if(vault_save(app)) {
            // Overwrite the plain-text secrets before deleting the file.
            memset(buf, 0, len);
            file_write_all(app->storage, IMPORT_PATH, (const uint8_t*)buf, len);
            storage_simply_remove(app->storage, IMPORT_PATH);
            snprintf(text, sizeof(text), s->imp_done, (unsigned)added_count);
            set_msg(app, text);
        } else {
            app->acc_count = old_count;
            set_msg(app, s->msg_save_fail);
        }
    }

    secure_zero(added, sizeof(added));
    secure_zero(buf, IMPORT_MAX + 1);
    free(buf);
}

//======================================================================================================================
// Time, codes and USB typing
//======================================================================================================================

static uint32_t utc_now(const App* app) {
    DateTime dt;
    furi_hal_rtc_get_datetime(&dt);
    int64_t ts = (int64_t)datetime_datetime_to_timestamp(&dt) - (int64_t)app->utc_min * 60;
    return ts < 0 ? 0 : (uint32_t)ts;
}

static bool clock_looks_wrong(void) {
    DateTime dt;
    furi_hal_rtc_get_datetime(&dt);
    return dt.year < APP_START_YEAR;
}

static uint32_t account_code(const App* app, const Account* a) {
    return totp_code(
        (OtpAlgo)a->algo, a->secret, a->secret_len, utc_now(app), a->period, a->digits);
}

static uint16_t hid_digit_key(bool numpad, char digit) {
    uint16_t d = (uint16_t)(digit - '0');
    if(numpad) return d == 0 ? 0x62 : (uint16_t)(0x59 + d - 1);
    return d == 0 ? 0x27 : (uint16_t)(0x1e + d - 1);
}

static void action_type(App* app) {
    const LangStrings* s = LANGUAGES[app->lang];
    const Account* a = &app->acc[app->sel];
    char digits[12];
    snprintf(digits, sizeof(digits), "%0*lu", (int)a->digits, (unsigned long)account_code(app, a));

    FuriHalUsbInterface* previous = furi_hal_usb_get_config();
    furi_hal_usb_unlock();
    furi_hal_usb_set_config(&usb_hid, NULL);

    uint32_t waited = 0;
    while(!furi_hal_hid_is_connected() && waited < 3000) {
        furi_delay_ms(50);
        waited += 50;
    }

    if(furi_hal_hid_is_connected()) {
        furi_delay_ms(300);
        for(const char* p = digits; *p; p++) {
            uint16_t key = hid_digit_key(app->digits_pad != 0, *p);
            furi_hal_hid_kb_press(key);
            furi_delay_ms(25);
            furi_hal_hid_kb_release(key);
            furi_delay_ms(25);
        }
        set_msg(app, s->msg_typed);
    } else {
        set_msg(app, s->msg_no_usb);
    }

    furi_hal_usb_set_config(previous, NULL);
    secure_zero(digits, sizeof(digits));
}

//======================================================================================================================
// Create / unlock / lock
//======================================================================================================================

static void wipe_password(App* app) {
    secure_zero(app->pw, sizeof(app->pw));
    secure_zero(app->pw_first, sizeof(app->pw_first));
    app->pw_len = 0;
    app->pw_cur = 0;
}

static void lock_vault(App* app) {
    secure_zero(app->key, sizeof(app->key));
    secure_zero(app->acc, sizeof(app->acc));
    app->acc_count = 0;
    app->sel = 0;
    app->page = PAGE_CODES;
    wipe_password(app);
    app->screen = ScreenUnlock;
}

static void action_create(App* app) {
    const LangStrings* s = LANGUAGES[app->lang];
    furi_hal_random_fill_buf(app->salt, SALT_LEN);
    app->iters = calibrate_iterations();
    app->acc_count = 0;

    if(derive_key(app->pw, app->salt, app->iters, app->key) && vault_save(app)) {
        wipe_password(app);
        app->page = PAGE_CODES;
        app->screen = ScreenMain;
    } else {
        secure_zero(app->key, sizeof(app->key));
        wipe_password(app);
        set_msg(app, s->msg_save_fail);
        app->screen = ScreenCreate;
    }
}

static void action_unlock(App* app) {
    const LangStrings* s = LANGUAGES[app->lang];
    VaultResult r = vault_load(app);
    if(r == VaultOk) {
        app->fails = 0;
        wipe_password(app);
        app->page = PAGE_CODES;
        app->screen = ScreenMain;
    } else if(r == VaultWrongPassword) {
        app->fails++;
        if(app->fails >= 3) {
            uint32_t shift = app->fails - 3;
            uint32_t secs = shift > 5 ? 120 : (5u << shift);
            if(secs > 120) secs = 120;
            app->wait_until = furi_get_tick() + secs * 1000;
        }
        wipe_password(app);
        set_msg(app, s->msg_wrong);
    } else {
        wipe_password(app);
        set_msg(app, s->msg_corrupt);
    }
}

static void run_action(App* app, Action act) {
    switch(act) {
    case ActCreate:
        action_create(app);
        break;
    case ActUnlock:
        action_unlock(app);
        break;
    case ActImport:
        action_import(app);
        break;
    case ActType:
        action_type(app);
        break;
    default:
        break;
    }
}

//======================================================================================================================
// Drawing
//======================================================================================================================

static void draw_header(Canvas* canvas, const char* title, const char* indicator) {
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, title);
    canvas_set_font(canvas, FontSecondary);
    if(indicator) canvas_draw_str_aligned(canvas, 126, 2, AlignRight, AlignTop, indicator);
    canvas_draw_line(canvas, 0, 13, 127, 13);
}

static void draw_password_screen(Canvas* canvas, const App* app, const LangStrings* s) {
    const char* title = app->screen == ScreenCreate  ? s->title_create :
                        app->screen == ScreenConfirm ? s->title_confirm :
                                                       s->title_unlock;
    draw_header(canvas, title, NULL);

    char stars[PW_MAX + 1];
    memset(stars, '*', app->pw_len);
    stars[app->pw_len] = 0;
    canvas_draw_str(canvas, 2, 26, stars);

    char cur[2] = {PW_CHARSET[app->pw_cur], 0};
    canvas_draw_frame(canvas, 2, 29, 14, 13);
    canvas_draw_str_aligned(canvas, 9, 36, AlignCenter, AlignCenter, cur);
    canvas_draw_str(canvas, 20, 39, s->pw_hint1);
    canvas_draw_str(canvas, 2, 51, s->pw_hint2);

    char text[40];
    if(app->msg_until && (int32_t)(app->msg_until - furi_get_tick()) > 0) {
        canvas_draw_str(canvas, 2, 62, app->msg);
    } else if(app->screen == ScreenUnlock && is_waiting(app)) {
        uint32_t secs = (app->wait_until - furi_get_tick() + 999) / 1000;
        snprintf(text, sizeof(text), s->msg_wait, (unsigned long)secs);
        canvas_draw_str(canvas, 2, 62, text);
    } else {
        canvas_draw_str(canvas, 2, 62, s->pw_hint3);
    }
}

static void draw_codes_page(Canvas* canvas, const App* app, const LangStrings* s) {
    char text[40];
    if(app->acc_count == 0) {
        canvas_draw_str_aligned(canvas, 64, 34, AlignCenter, AlignBottom, s->no_accounts);
        canvas_draw_str_aligned(canvas, 64, 46, AlignCenter, AlignBottom, s->no_accounts_hint);
        return;
    }

    const Account* a = &app->acc[app->sel];
    canvas_draw_str_aligned(canvas, 64, 25, AlignCenter, AlignBottom, a->name);

    char digits[12];
    snprintf(digits, sizeof(digits), "%0*lu", (int)a->digits, (unsigned long)account_code(app, a));
    char left[8] = {0};
    char right[8] = {0};
    size_t half = a->digits / 2;
    memcpy(left, digits, half);
    memcpy(right, digits + half, a->digits - half);
    canvas_set_font(canvas, FontBigNumbers);
    canvas_draw_str_aligned(canvas, 60, 44, AlignRight, AlignBottom, left);
    canvas_draw_str_aligned(canvas, 68, 44, AlignLeft, AlignBottom, right);
    canvas_set_font(canvas, FontSecondary);

    uint32_t remaining = a->period - (utc_now(app) % a->period);
    canvas_draw_frame(canvas, 2, 49, 124, 5);
    canvas_draw_box(canvas, 4, 51, (uint8_t)(remaining * 120 / a->period), 1);

    if(clock_looks_wrong()) {
        canvas_draw_str(canvas, 2, 63, s->clock_warn);
    } else {
        canvas_draw_str(canvas, 2, 63, s->hint_type);
    }
    snprintf(text, sizeof(text), "%u/%u", app->sel + 1, app->acc_count);
    canvas_draw_str_aligned(canvas, 126, 63, AlignRight, AlignBottom, text);
}

static void draw_import_page(Canvas* canvas, const App* app, const LangStrings* s) {
    canvas_draw_str(canvas, 2, 24, s->imp_1);
    canvas_draw_str(canvas, 2, 33, s->imp_2);
    canvas_draw_str(canvas, 2, 42, s->imp_3);
    canvas_draw_str(canvas, 2, 52, s->imp_ok);
    if(app->msg_until && (int32_t)(app->msg_until - furi_get_tick()) > 0) {
        canvas_draw_str(canvas, 2, 62, app->msg);
    }
}

static void draw_settings_page(Canvas* canvas, const App* app, const LangStrings* s) {
    const char* labels[SETTINGS_ROWS] = {s->lbl_language, s->lbl_utc, s->lbl_digits, s->lbl_lock};
    char values[SETTINGS_ROWS][20];
    snprintf(values[SET_LANGUAGE], sizeof(values[0]), "%s", LANGUAGES[app->lang]->lang_name);
    int abs_min = app->utc_min < 0 ? -app->utc_min : app->utc_min;
    snprintf(
        values[SET_UTC],
        sizeof(values[0]),
        "%c%02d:%02d",
        app->utc_min < 0 ? '-' : '+',
        abs_min / 60,
        abs_min % 60);
    snprintf(
        values[SET_DIGITS],
        sizeof(values[0]),
        "%s",
        app->digits_pad ? s->digits_pad : s->digits_top);
    uint16_t lock_secs = LOCK_SECONDS[app->lock_idx];
    if(lock_secs < 60) {
        snprintf(values[SET_LOCK], sizeof(values[0]), "%u s", lock_secs);
    } else {
        snprintf(values[SET_LOCK], sizeof(values[0]), "%u min", lock_secs / 60);
    }

    for(uint8_t i = 0; i < SETTINGS_ROWS; i++) {
        uint8_t y = 25 + i * 10;
        if(i == app->settings_sel) canvas_draw_str(canvas, 0, y, ">");
        canvas_draw_str(canvas, 7, y, labels[i]);
        canvas_draw_str(canvas, 70, y, values[i]);
    }
}

static void draw_help_page(Canvas* canvas, const LangStrings* s) {
    canvas_draw_str(canvas, 2, 24, s->help_1);
    canvas_draw_str(canvas, 2, 33, s->help_2);
    canvas_draw_str(canvas, 2, 42, s->help_3);
    canvas_draw_str(canvas, 2, 51, s->help_4);
    canvas_draw_str(canvas, 2, 60, s->help_5);
}

static void draw_about_page(Canvas* canvas, const App* app, const LangStrings* s) {
    DateTime dt;
    furi_hal_rtc_get_datetime(&dt);
    char text[24];

    canvas_draw_str(canvas, 2, 24, s->about_version);
    snprintf(text, sizeof(text), "v%s", APP_VERSION);
    canvas_draw_str(canvas, 62, 24, text);

    canvas_draw_str(canvas, 2, 33, s->about_author);
    canvas_draw_str(canvas, 62, 33, APP_AUTHOR);

    canvas_draw_str(canvas, 2, 42, s->about_copyright);
    if(dt.year > APP_START_YEAR) {
        snprintf(text, sizeof(text), "%u-%u", APP_START_YEAR, dt.year);
    } else {
        snprintf(text, sizeof(text), "%u", APP_START_YEAR);
    }
    canvas_draw_str(canvas, 62, 42, text);

    canvas_draw_str(canvas, 2, 51, s->about_license);
    canvas_draw_str(canvas, 62, 51, APP_LICENSE);

    canvas_draw_str(canvas, 2, 60, s->about_selftest);
    canvas_draw_str(canvas, 62, 60, app->selftest_ok ? s->selftest_ok : s->selftest_fail);
}

// Shown instead of everything else when the self-test fails: the crypto code
// cannot be trusted, so the app refuses to create or open a vault.
static void draw_error_screen(Canvas* canvas, const App* app, const LangStrings* s) {
    char text[32];
    canvas_draw_box(canvas, 0, 0, 128, 18);
    canvas_set_color(canvas, ColorWhite);
    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str_aligned(canvas, 64, 9, AlignCenter, AlignCenter, s->err_title);
    canvas_set_color(canvas, ColorBlack);
    canvas_draw_str_aligned(canvas, 64, 33, AlignCenter, AlignCenter, s->err_use);
    canvas_set_font(canvas, FontSecondary);
    snprintf(text, sizeof(text), s->err_step, (unsigned)app->selftest_step);
    canvas_draw_str_aligned(canvas, 64, 46, AlignCenter, AlignCenter, text);
    canvas_draw_str_aligned(canvas, 64, 58, AlignCenter, AlignCenter, s->err_exit);
    canvas_draw_frame(canvas, 0, 0, 128, 64);
}

static void draw_callback(Canvas* canvas, void* ctx) {
    App* app = ctx;
    furi_mutex_acquire(app->mutex, FuriWaitForever);
    const LangStrings* s = LANGUAGES[app->lang];

    canvas_clear(canvas);
    canvas_set_color(canvas, ColorBlack);
    canvas_set_font(canvas, FontSecondary);

    if(!app->selftest_ok) {
        draw_error_screen(canvas, app, s);
    } else if(app->busy) {
        canvas_draw_str_aligned(canvas, 64, 32, AlignCenter, AlignCenter, s->msg_working);
    } else if(app->screen != ScreenMain) {
        draw_password_screen(canvas, app, s);
    } else {
        const char* titles[PAGE_COUNT] = {
            s->title_codes, s->title_import, s->title_settings, s->title_help, s->title_about};
        char indicator[8];
        snprintf(indicator, sizeof(indicator), "%d/%d", app->page + 1, PAGE_COUNT);
        draw_header(canvas, titles[app->page], indicator);

        switch(app->page) {
        case PAGE_CODES:
            draw_codes_page(canvas, app, s);
            break;
        case PAGE_IMPORT:
            draw_import_page(canvas, app, s);
            break;
        case PAGE_SETTINGS:
            draw_settings_page(canvas, app, s);
            break;
        case PAGE_HELP:
            draw_help_page(canvas, s);
            break;
        default:
            draw_about_page(canvas, app, s);
            break;
        }
    }

    furi_mutex_release(app->mutex);
}

static void input_callback(InputEvent* event, void* ctx) {
    App* app = ctx;
    furi_message_queue_put(app->queue, event, 0);
}

//======================================================================================================================
// Input
//======================================================================================================================

static void settings_change(App* app) {
    switch(app->settings_sel) {
    case SET_LANGUAGE:
        app->lang = (uint8_t)((app->lang + 1) % LANGUAGE_COUNT);
        break;
    case SET_UTC:
        app->utc_min = (int16_t)(app->utc_min + 30);
        if(app->utc_min > UTC_MAX_MINUTES) app->utc_min = UTC_MIN_MINUTES;
        break;
    case SET_DIGITS:
        app->digits_pad = app->digits_pad ? 0 : 1;
        break;
    default:
        app->lock_idx = (uint8_t)((app->lock_idx + 1) % LOCK_COUNT);
        break;
    }
    settings_save(app);
}

// Returns false when the app should exit.
static bool handle_password_input(App* app, const InputEvent* event) {
    const LangStrings* s = LANGUAGES[app->lang];
    size_t charset_len = strlen(PW_CHARSET);

    switch(event->key) {
    case InputKeyUp:
        app->pw_cur = (uint8_t)((app->pw_cur + charset_len - 1) % charset_len);
        break;
    case InputKeyDown:
        app->pw_cur = (uint8_t)((app->pw_cur + 1) % charset_len);
        break;
    case InputKeyRight:
        if(app->pw_len < PW_MAX) {
            app->pw[app->pw_len++] = PW_CHARSET[app->pw_cur];
            app->pw[app->pw_len] = 0;
        }
        break;
    case InputKeyLeft:
        if(app->pw_len) app->pw[--app->pw_len] = 0;
        break;
    case InputKeyOk:
        if(app->screen == ScreenCreate) {
            if(app->pw_len < PW_MIN) {
                set_msg(app, s->msg_short);
            } else {
                memcpy(app->pw_first, app->pw, sizeof(app->pw));
                secure_zero(app->pw, sizeof(app->pw));
                app->pw_len = 0;
                app->screen = ScreenConfirm;
            }
        } else if(app->screen == ScreenConfirm) {
            if(strcmp(app->pw, app->pw_first) != 0) {
                wipe_password(app);
                set_msg(app, s->msg_mismatch);
                app->screen = ScreenCreate;
            } else {
                app->pending = ActCreate;
            }
        } else if(app->pw_len > 0 && !is_waiting(app)) {
            app->pending = ActUnlock;
        }
        break;
    case InputKeyBack:
        if(app->screen == ScreenConfirm) {
            wipe_password(app);
            app->screen = ScreenCreate;
        } else {
            return false;
        }
        break;
    default:
        break;
    }
    return true;
}

static bool handle_main_input(App* app, const InputEvent* event) {
    switch(event->key) {
    case InputKeyRight:
        app->page = (uint8_t)((app->page + 1) % PAGE_COUNT);
        break;
    case InputKeyLeft:
        app->page = (uint8_t)((app->page + PAGE_COUNT - 1) % PAGE_COUNT);
        break;
    case InputKeyDown:
    case InputKeyUp: {
        int step = event->key == InputKeyDown ? 1 : -1;
        if(app->page == PAGE_CODES && app->acc_count) {
            app->sel = (uint8_t)((app->sel + step + app->acc_count) % app->acc_count);
        } else if(app->page == PAGE_SETTINGS) {
            app->settings_sel = (uint8_t)((app->settings_sel + step + SETTINGS_ROWS) % SETTINGS_ROWS);
        }
        break;
    }
    case InputKeyOk:
        if(app->page == PAGE_CODES && app->acc_count) {
            app->pending = ActType;
        } else if(app->page == PAGE_IMPORT) {
            app->pending = ActImport;
        } else if(app->page == PAGE_SETTINGS) {
            settings_change(app);
        }
        break;
    case InputKeyBack:
        if(app->page != PAGE_CODES) {
            app->page = PAGE_CODES;
        } else {
            return false;
        }
        break;
    default:
        break;
    }
    return true;
}

// Returns false when the app should exit.
static bool handle_input(App* app, const InputEvent* event) {
    if(event->type == InputTypeLong && event->key == InputKeyBack) return false;
    if(!app->selftest_ok) return !(event->type == InputTypeShort && event->key == InputKeyBack);
    bool repeatable = event->key == InputKeyUp || event->key == InputKeyDown;
    if(event->type != InputTypeShort && !(event->type == InputTypeRepeat && repeatable)) {
        return true;
    }
    app->last_input = furi_get_tick();
    if(app->screen == ScreenMain) return handle_main_input(app, event);
    return handle_password_input(app, event);
}

//======================================================================================================================
// Entry point
//======================================================================================================================

int32_t otp_vault_app(void* p) {
    UNUSED(p);

    App* app = malloc(sizeof(App));
    memset(app, 0, sizeof(App));
    app->lang = 0;
    for(size_t i = 0; i < LANGUAGE_COUNT; i++) {
        if(strcmp(LANGUAGES[i]->lang_name, "English") == 0) app->lang = (uint8_t)i;
    }
    app->utc_min = 60;
    app->lock_idx = LOCK_DEFAULT_IDX;
    app->mutex = furi_mutex_alloc(FuriMutexTypeNormal);
    app->queue = furi_message_queue_alloc(8, sizeof(InputEvent));
    app->storage = furi_record_open(RECORD_STORAGE);

    settings_load(app);
    app->selftest_step = run_selftest();
    app->selftest_ok = app->selftest_step == 0;
    selftest_log(app);
    app->screen = storage_file_exists(app->storage, VAULT_PATH) ? ScreenUnlock : ScreenCreate;
    app->last_input = furi_get_tick();

    app->view_port = view_port_alloc();
    view_port_draw_callback_set(app->view_port, draw_callback, app);
    view_port_input_callback_set(app->view_port, input_callback, app);
    app->gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(app->gui, app->view_port, GuiLayerFullscreen);

    bool run = true;
    while(run) {
        InputEvent event;
        FuriStatus status = furi_message_queue_get(app->queue, &event, 200);

        furi_mutex_acquire(app->mutex, FuriWaitForever);
        if(status == FuriStatusOk) run = handle_input(app, &event);
        if(!app->selftest_ok && app->pending != ActNone) app->pending = ActNone;

        if(app->screen == ScreenMain &&
           furi_get_tick() - app->last_input > (uint32_t)LOCK_SECONDS[app->lock_idx] * 1000) {
            lock_vault(app);
        }

        Action act = app->pending;
        app->pending = ActNone;
        if(act != ActNone) app->busy = true;
        furi_mutex_release(app->mutex);
        view_port_update(app->view_port);

        if(act != ActNone) {
            // The GUI thread only draws "Working..." while busy is set, so the
            // heavy work below can run without holding the mutex.
            furi_delay_ms(120);
            run_action(app, act);
            furi_mutex_acquire(app->mutex, FuriWaitForever);
            app->busy = false;
            app->last_input = furi_get_tick();
            furi_mutex_release(app->mutex);
            view_port_update(app->view_port);
        }
    }

    gui_remove_view_port(app->gui, app->view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(app->view_port);
    furi_record_close(RECORD_STORAGE);
    furi_message_queue_free(app->queue);
    furi_mutex_free(app->mutex);
    secure_zero(app, sizeof(App));
    free(app);
    return 0;
}
