/*
 * Device Info - Flipper Zero app
 * Copyright (c) 2026 Eric M. Kok
 * SPDX-License-Identifier: GPL-3.0-only
 * See LICENSE in this app's folder for the full license text.
 */

#include <furi.h>
#include <furi_hal.h>
#include <furi_hal_version.h>
#include <furi_hal_power.h>
#include <gui/gui.h>
#include <input/input.h>
#include <storage/storage.h>
#include <flipper_format/flipper_format.h>

#include <stdio.h>
#include <string.h>

#define APP_VERSION "1.13"
#define APP_START_YEAR 2026
#define APP_AUTHOR "Eric M. Kok"
#define APP_LICENSE "GPLv3"

#define SCREEN_W 128
#define SCREEN_H 64

// Milliseconds between forced redraws, so the live pages (battery, time)
// keep ticking while the user leaves them on screen.
#define REFRESH_MS 1000

#define PAGE_DEVICE 0
#define PAGE_FIRMWARE 1
#define PAGE_BATTERY 2
#define PAGE_STORAGE 3
#define PAGE_IDS 4
#define PAGE_ABOUT 5
#define PAGE_COUNT 6

#define MAX_LINES 5
#define LINE_LENGTH 40
#define HEX_LENGTH 24

#define LANGUAGE_VISIBLE 4

typedef struct {
    const char* lang_name;

    const char* title_device;
    const char* title_firmware;
    const char* title_battery;
    const char* title_storage;
    const char* title_ids;
    const char* title_about;
    const char* title_language;

    const char* lbl_name;
    const char* lbl_model;
    const char* lbl_hw;
    const char* word_target;
    const char* lbl_color;
    const char* color_black;
    const char* color_white;
    const char* color_transparent;
    const char* color_unknown;

    const char* lbl_version;
    const char* lbl_branch;
    const char* lbl_commit;
    const char* lbl_build;

    const char* lbl_level;
    const char* word_healthy;
    const char* lbl_status;
    const char* status_charging;
    const char* status_discharging;
    const char* lbl_voltage;
    const char* lbl_current;

    const char* lbl_total;
    const char* lbl_free;
    const char* lbl_used;
    const char* msg_no_sd;

    const char* lbl_uid;
    const char* lbl_ble;
    const char* lbl_date;
    const char* lbl_time;

    const char* about_version_label;
    const char* about_author_label;
    const char* about_license_label;
    const char* about_hint;
} LangStrings;

// Generated by pre_build.ps1 from files/lang_*.h - see that script to add a
// language without touching this file.
#include "lang_manifest.h"

typedef enum {
    ScreenLanguagePicker,
    ScreenInfo,
} AppScreen;

typedef struct {
    FuriMutex* mutex;
    int page;
    int lang_index;
    int lang_selection;
    bool language_confirmed;
    AppScreen screen;
    ViewPort* view_port;
} DeviceInfoApp;

static void save_settings(Storage* storage, int lang_index) {
    FuriString* path = furi_string_alloc_printf(APP_DATA_PATH("settings.txt"));
    storage_common_resolve_path_and_ensure_app_directory(storage, path);

    FlipperFormat* ff = flipper_format_file_alloc(storage);
    do {
        if(!flipper_format_file_open_always(ff, furi_string_get_cstr(path))) break;
        if(!flipper_format_write_header_cstr(ff, "Device Info Settings", 1)) break;
        uint32_t value = (uint32_t)lang_index;
        flipper_format_write_uint32(ff, "Language", &value, 1);
    } while(false);
    flipper_format_file_close(ff);
    flipper_format_free(ff);
    furi_string_free(path);
}

static bool load_settings(Storage* storage, int* out_lang_index) {
    FuriString* path = furi_string_alloc_printf(APP_DATA_PATH("settings.txt"));
    storage_common_resolve_path_and_ensure_app_directory(storage, path);

    FlipperFormat* ff = flipper_format_file_alloc(storage);
    FuriString* filetype = furi_string_alloc();
    bool ok = false;
    do {
        if(!flipper_format_file_open_existing(ff, furi_string_get_cstr(path))) break;
        uint32_t version = 0;
        if(!flipper_format_read_header(ff, filetype, &version)) break;
        uint32_t value = 0;
        if(!flipper_format_read_uint32(ff, "Language", &value, 1)) break;
        if(value >= LANGUAGE_COUNT) break;
        *out_lang_index = (int)value;
        ok = true;
    } while(false);
    furi_string_free(filetype);
    flipper_format_file_close(ff);
    flipper_format_free(ff);
    furi_string_free(path);
    return ok;
}

static const char* hw_color_name(const LangStrings* s, FuriHalVersionColor color) {
    switch(color) {
    case FuriHalVersionColorBlack:
        return s->color_black;
    case FuriHalVersionColorWhite:
        return s->color_white;
    case FuriHalVersionColorTransparent:
        return s->color_transparent;
    default:
        return s->color_unknown;
    }
}

static void format_hex(const uint8_t* data, size_t len, char* out, size_t out_size) {
    size_t pos = 0;
    for(size_t i = 0; i < len && pos + 2 < out_size; i++) {
        pos += snprintf(out + pos, out_size - pos, "%02X", data[i]);
    }
}

static void format_mac(const uint8_t* mac, char* out, size_t out_size) {
    snprintf(
        out,
        out_size,
        "%02X:%02X:%02X:%02X:%02X:%02X",
        mac[0],
        mac[1],
        mac[2],
        mac[3],
        mac[4],
        mac[5]);
}

// Formats `value` with a dot as thousands separator, e.g. 15245 -> "15.245".
static void format_thousands(uint64_t value, char* out, size_t out_size) {
    char digits[24];
    snprintf(digits, sizeof(digits), "%llu", (unsigned long long)value);
    size_t digit_count = strlen(digits);

    size_t pos = 0;
    for(size_t i = 0; i < digit_count && pos + 1 < out_size; i++) {
        if(i > 0 && (digit_count - i) % 3 == 0 && pos + 1 < out_size) {
            out[pos++] = '.';
        }
        out[pos++] = digits[i];
    }
    out[pos] = '\0';
}

// Fills `lines` (up to MAX_LINES entries of LINE_LENGTH chars) with the
// content for the given page. For pages that want a right-aligned value
// column, `values[i]` is set to the value and `lines[i]` holds just the
// label; otherwise `values[i]` is left empty and `lines[i]` holds the full
// text. Returns the number of lines filled.
static size_t build_page_lines(
    const LangStrings* s,
    int page,
    char lines[MAX_LINES][LINE_LENGTH],
    char values[MAX_LINES][LINE_LENGTH]) {
    size_t n = 0;
    for(size_t i = 0; i < MAX_LINES; i++) {
        values[i][0] = '\0';
    }

    if(page == PAGE_DEVICE) {
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_name);
        snprintf(values[n], LINE_LENGTH, "%s", furi_hal_version_get_device_name_ptr());
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_model);
        snprintf(values[n], LINE_LENGTH, "%s", furi_hal_version_get_model_name());
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_hw);
        snprintf(
            values[n],
            LINE_LENGTH,
            "v%u %s %u",
            furi_hal_version_get_hw_version(),
            s->word_target,
            furi_hal_version_get_hw_target());
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_color);
        snprintf(values[n], LINE_LENGTH, "%s", hw_color_name(s, furi_hal_version_get_hw_color()));
        n++;
    } else if(page == PAGE_FIRMWARE) {
        const Version* v = furi_hal_version_get_firmware_version();
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_version);
        snprintf(values[n], LINE_LENGTH, "%s", version_get_version(v));
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_branch);
        snprintf(values[n], LINE_LENGTH, "%s", version_get_gitbranch(v));
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_commit);
        snprintf(
            values[n],
            LINE_LENGTH,
            "%.7s%s",
            version_get_githash(v),
            version_get_dirty_flag(v) ? "*" : "");
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_build);
        snprintf(values[n], LINE_LENGTH, "%s", version_get_builddate(v));
        n++;
    } else if(page == PAGE_BATTERY) {
        uint8_t pct = furi_hal_power_get_pct();
        uint8_t health = furi_hal_power_get_bat_health_pct();
        bool charging = furi_hal_power_is_charging();
        float voltage = furi_hal_power_get_battery_voltage(FuriHalPowerICFuelGauge);
        float current = furi_hal_power_get_battery_current(FuriHalPowerICFuelGauge);

        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_level);
        snprintf(values[n], LINE_LENGTH, "%u%% (%u%% %s)", pct, health, s->word_healthy);
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_status);
        snprintf(values[n], LINE_LENGTH, "%s", charging ? s->status_charging : s->status_discharging);
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_voltage);
        snprintf(values[n], LINE_LENGTH, "%.2f V", (double)voltage);
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_current);
        snprintf(values[n], LINE_LENGTH, "%.2f A", (double)current);
        n++;
    } else if(page == PAGE_STORAGE) {
        Storage* storage = furi_record_open(RECORD_STORAGE);
        uint64_t total_space = 0;
        uint64_t free_space = 0;
        FS_Error error = storage_common_fs_info(storage, "/ext", &total_space, &free_space);
        furi_record_close(RECORD_STORAGE);

        if(error == FSE_OK) {
            uint64_t total_mb = total_space / (1024 * 1024);
            uint64_t free_mb = free_space / (1024 * 1024);
            uint64_t used_mb = total_mb - free_mb;

            char total_str[HEX_LENGTH];
            char free_str[HEX_LENGTH];
            char used_str[HEX_LENGTH];
            format_thousands(total_mb, total_str, sizeof(total_str));
            format_thousands(free_mb, free_str, sizeof(free_str));
            format_thousands(used_mb, used_str, sizeof(used_str));

            snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_total);
            snprintf(values[n], LINE_LENGTH, "%s MB", total_str);
            n++;
            snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_free);
            snprintf(values[n], LINE_LENGTH, "%s MB", free_str);
            n++;
            snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_used);
            snprintf(values[n], LINE_LENGTH, "%s MB", used_str);
            n++;
        } else {
            snprintf(lines[n++], LINE_LENGTH, "%s", s->msg_no_sd);
        }
    } else if(page == PAGE_IDS) {
        char uid_hex[HEX_LENGTH];
        format_hex(furi_hal_version_uid(), furi_hal_version_uid_size(), uid_hex, sizeof(uid_hex));
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_uid);
        snprintf(values[n], LINE_LENGTH, "%s", uid_hex);
        n++;

        char mac_hex[HEX_LENGTH];
        format_mac(furi_hal_version_get_ble_mac(), mac_hex, sizeof(mac_hex));
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_ble);
        snprintf(values[n], LINE_LENGTH, "%s", mac_hex);
        n++;

        DateTime datetime;
        furi_hal_rtc_get_datetime(&datetime);
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_date);
        snprintf(
            values[n], LINE_LENGTH, "%02u-%02u-%04u", datetime.day, datetime.month, datetime.year);
        n++;
        snprintf(lines[n], LINE_LENGTH, "%s", s->lbl_time);
        snprintf(
            values[n],
            LINE_LENGTH,
            "%02u:%02u:%02u",
            datetime.hour,
            datetime.minute,
            datetime.second);
        n++;
    } else if(page == PAGE_ABOUT) {
        DateTime datetime;
        furi_hal_rtc_get_datetime(&datetime);

        snprintf(lines[n], LINE_LENGTH, "%s", s->about_version_label);
        snprintf(values[n], LINE_LENGTH, "Device Info v%s", APP_VERSION);
        n++;

        snprintf(lines[n], LINE_LENGTH, "%s", s->about_author_label);
        snprintf(values[n], LINE_LENGTH, "%s", APP_AUTHOR);
        n++;

        snprintf(lines[n], LINE_LENGTH, "Copyright:");
        if(datetime.year > APP_START_YEAR) {
            snprintf(values[n], LINE_LENGTH, "%u-%u", APP_START_YEAR, datetime.year);
        } else {
            snprintf(values[n], LINE_LENGTH, "%u", APP_START_YEAR);
        }
        n++;

        snprintf(lines[n], LINE_LENGTH, "%s", s->about_license_label);
        snprintf(values[n], LINE_LENGTH, "%s", APP_LICENSE);
        n++;

        snprintf(lines[n++], LINE_LENGTH, "%s", s->about_hint);
    }

    return n;
}

static void draw_info_screen(Canvas* canvas, const LangStrings* s, int page) {
    char lines[MAX_LINES][LINE_LENGTH];
    char values[MAX_LINES][LINE_LENGTH];
    size_t line_count = build_page_lines(s, page, lines, values);

    const char* titles[PAGE_COUNT] = {
        s->title_device,
        s->title_firmware,
        s->title_battery,
        s->title_storage,
        s->title_ids,
        s->title_about,
    };

    canvas_clear(canvas);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, titles[page]);
    if(page != PAGE_ABOUT) {
        canvas_draw_line(canvas, 0, 13, SCREEN_W, 13);
    }

    canvas_set_font(canvas, page == PAGE_STORAGE ? FontKeyboard : FontSecondary);
    uint32_t y = page == PAGE_ABOUT ? 20 : 24;
    uint32_t y_step = page == PAGE_ABOUT ? 9 : 10;
    for(size_t i = 0; i < line_count; i++) {
        canvas_draw_str(canvas, 2, y, lines[i]);
        if(values[i][0] != '\0') {
            canvas_draw_str_aligned(
                canvas, SCREEN_W - 2, y, AlignRight, AlignBottom, values[i]);
        }
        y += y_step;
    }

    char page_indicator[16];
    snprintf(page_indicator, sizeof(page_indicator), "%d/%d", page + 1, PAGE_COUNT);
    canvas_draw_str_aligned(
        canvas, SCREEN_W - 2, SCREEN_H - 2, AlignRight, AlignBottom, page_indicator);
}

static void draw_language_picker(Canvas* canvas, int selection, int active) {
    canvas_clear(canvas);

    canvas_set_font(canvas, FontPrimary);
    canvas_draw_str(canvas, 2, 10, LANGUAGES[selection]->title_language);
    canvas_draw_line(canvas, 0, 13, SCREEN_W, 13);

    canvas_set_font(canvas, FontSecondary);

    int scroll = 0;
    if(selection >= LANGUAGE_VISIBLE) scroll = selection - LANGUAGE_VISIBLE + 1;
    if(scroll > (int)LANGUAGE_COUNT - LANGUAGE_VISIBLE) scroll = (int)LANGUAGE_COUNT - LANGUAGE_VISIBLE;
    if(scroll < 0) scroll = 0;

    uint32_t y = 24;
    for(int i = scroll; i < scroll + LANGUAGE_VISIBLE && i < (int)LANGUAGE_COUNT; i++) {
        char line[LINE_LENGTH];
        snprintf(
            line,
            LINE_LENGTH,
            "%s%s%s",
            i == selection ? "> " : "  ",
            LANGUAGES[i]->lang_name,
            i == active ? " *" : "");
        canvas_draw_str(canvas, 2, y, line);
        y += 10;
    }
}

static void draw_callback(Canvas* canvas, void* context) {
    DeviceInfoApp* app = context;

    AppScreen screen;
    int page, lang_index, lang_selection;
    furi_mutex_acquire(app->mutex, FuriWaitForever);
    screen = app->screen;
    page = app->page;
    lang_index = app->lang_index;
    lang_selection = app->lang_selection;
    furi_mutex_release(app->mutex);

    if(screen == ScreenLanguagePicker) {
        draw_language_picker(canvas, lang_selection, lang_index);
    } else {
        draw_info_screen(canvas, LANGUAGES[lang_index], page);
    }
}

static void input_callback(InputEvent* input_event, void* context) {
    FuriMessageQueue* event_queue = context;
    furi_message_queue_put(event_queue, input_event, FuriWaitForever);
}

static void timer_callback(void* context) {
    DeviceInfoApp* app = context;
    view_port_update(app->view_port);
}

int32_t device_info_app(void* p) {
    UNUSED(p);

    DeviceInfoApp app = {0};
    app.mutex = furi_mutex_alloc(FuriMutexTypeNormal);

    Storage* storage = furi_record_open(RECORD_STORAGE);
    int saved_lang = 0;
    if(load_settings(storage, &saved_lang)) {
        app.lang_index = saved_lang;
        app.language_confirmed = true;
        app.screen = ScreenInfo;
    } else {
        app.lang_index = 0;
        app.language_confirmed = false;
        app.screen = ScreenLanguagePicker;
    }
    app.lang_selection = app.lang_index;
    furi_record_close(RECORD_STORAGE);

    FuriMessageQueue* event_queue = furi_message_queue_alloc(8, sizeof(InputEvent));

    ViewPort* view_port = view_port_alloc();
    app.view_port = view_port;
    view_port_draw_callback_set(view_port, draw_callback, &app);
    view_port_input_callback_set(view_port, input_callback, event_queue);

    Gui* gui = furi_record_open(RECORD_GUI);
    gui_add_view_port(gui, view_port, GuiLayerFullscreen);

    FuriTimer* timer = furi_timer_alloc(timer_callback, FuriTimerTypePeriodic, &app);
    furi_timer_start(timer, furi_ms_to_ticks(REFRESH_MS));

    InputEvent event;
    bool running = true;
    while(running) {
        FuriStatus status = furi_message_queue_get(event_queue, &event, FuriWaitForever);
        if(status != FuriStatusOk || event.type != InputTypeShort) continue;

        furi_mutex_acquire(app.mutex, FuriWaitForever);

        if(app.screen == ScreenLanguagePicker) {
            if(event.key == InputKeyDown) {
                app.lang_selection = (app.lang_selection + 1) % (int)LANGUAGE_COUNT;
            } else if(event.key == InputKeyUp) {
                app.lang_selection =
                    (app.lang_selection - 1 + (int)LANGUAGE_COUNT) % (int)LANGUAGE_COUNT;
            } else if(event.key == InputKeyOk) {
                app.lang_index = app.lang_selection;
                app.language_confirmed = true;
                Storage* s = furi_record_open(RECORD_STORAGE);
                save_settings(s, app.lang_index);
                furi_record_close(RECORD_STORAGE);
                app.screen = ScreenInfo;
            } else if(event.key == InputKeyBack) {
                if(app.language_confirmed) {
                    app.lang_selection = app.lang_index;
                    app.screen = ScreenInfo;
                }
            }
        } else {
            if(event.key == InputKeyBack) {
                running = false;
            } else if(event.key == InputKeyRight) {
                app.page = (app.page + 1) % PAGE_COUNT;
            } else if(event.key == InputKeyLeft) {
                app.page = (app.page - 1 + PAGE_COUNT) % PAGE_COUNT;
            } else if(event.key == InputKeyOk) {
                app.lang_selection = app.lang_index;
                app.screen = ScreenLanguagePicker;
            }
        }

        furi_mutex_release(app.mutex);
        view_port_update(view_port);
    }

    furi_timer_free(timer);
    gui_remove_view_port(gui, view_port);
    furi_record_close(RECORD_GUI);
    view_port_free(view_port);
    furi_message_queue_free(event_queue);
    furi_mutex_free(app.mutex);

    return 0;
}
