<#
Solar Calculator - Flipper Zero app
Copyright (c) 2026 Eric M. Kok
SPDX-License-Identifier: GPL-3.0-only
See LICENSE in this app's folder for the full license text.

Generates lang_manifest.h by scanning every files/lang_*.h file.
Invoked automatically by the build script just before ufbt.

To add a language: drop a new files/lang_<code>.h file containing
"static const LangStrings lang_<code> = { ... };" (same pattern as the
existing files) and rebuild. No change to solar_calculator.c is needed.
#>

$ErrorActionPreference = "Stop"

$appDir = $PSScriptRoot
$filesDir = Join-Path $appDir "files"
$manifestPath = Join-Path $appDir "lang_manifest.h"

$langFiles = Get-ChildItem -Path $filesDir -Filter "lang_*.h" -File | Sort-Object Name

if ($langFiles.Count -eq 0) {
    throw "No files/lang_*.h files found in '$filesDir'."
}

# Incremental: only regenerate when the language files have actually changed
# since last time. That is the case when:
#   1) lang_manifest.h does not exist yet, or
#   2) a files/lang_*.h is newer than lang_manifest.h (changed or added), or
#   3) a language file was removed (the include count no longer matches).
$needsRebuild = $false
$reason = ""

if (-not (Test-Path $manifestPath)) {
    $needsRebuild = $true
    $reason = "lang_manifest.h does not exist yet"
} else {
    $manifestTime = (Get-Item $manifestPath).LastWriteTimeUtc

    $newer = $langFiles | Where-Object { $_.LastWriteTimeUtc -gt $manifestTime }
    if ($newer) {
        $needsRebuild = $true
        $reason = "changed/added: " + (($newer | ForEach-Object { $_.Name }) -join ", ")
    } else {
        $manifestContent = Get-Content -Path $manifestPath -Raw
        $includeCount = ([regex]::Matches($manifestContent, 'include\s+"files/lang_')).Count
        if ($includeCount -ne $langFiles.Count) {
            $needsRebuild = $true
            $reason = "language file count changed ($includeCount -> $($langFiles.Count))"
        }
    }
}

if (-not $needsRebuild) {
    Write-Host "lang_manifest.h is up to date - no language file changed, skipping." -ForegroundColor DarkGray
    exit 0
}

$varNames = $langFiles | ForEach-Object { [System.IO.Path]::GetFileNameWithoutExtension($_.Name) }

$lines = @()
$lines += "#pragma once"
$lines += ""
$lines += "// SPDX-License-Identifier: GPL-3.0-only"
$lines += "// Copyright (c) 2026 Eric M. Kok"
$lines += "// AUTO-GENERATED by pre_build.ps1 - do not edit by hand."
$lines += "// Rebuilt on every build from files/lang_*.h."
$lines += ""
foreach ($f in $langFiles) {
    $lines += "#include ""files/$($f.Name)"""
}
$lines += ""
$lines += "static const LangStrings* const LANGUAGES[] = {"
foreach ($name in $varNames) {
    $lines += "    &$name,"
}
$lines += "};"
$lines += "#define LANGUAGE_COUNT (sizeof(LANGUAGES) / sizeof(LANGUAGES[0]))"
$lines += ""

Set-Content -Path $manifestPath -Value $lines -Encoding UTF8

Write-Host "lang_manifest.h rebuilt ($reason) from $($langFiles.Count) language file(s): $($varNames -join ', ')" -ForegroundColor Cyan
